// dok
as=document.getElementById('Cari');
const data=document.forms['masukan'];
  //run when kon is clicked
data.addEventListener('submit',function(e){
  e.preventDefault();
  if(as.value==''){
    alert('Masukan Nama Fitur Yang Ingin Di Cari');
  }else{
    window.location.href="#"+as.value.toLowerCase();
    window.location.reload();
  }
});
// nanti
var asem=window.location.href;
const semua=document.querySelector('#Semua');
const awal=document.querySelector('#awal');
const a1=document.querySelector('#a1');
const a2=document.querySelector('#a2');
const configurasi=document.querySelector('#configurasi');
const b1=document.querySelector('#b1');
const b2=document.querySelector('#b2');
const b3=document.querySelector('#b3');
const b4=document.querySelector('#b4');
const utama=document.querySelector('#utama');
const fitur=document.querySelector('#fitur');
const c1=document.querySelector('#c1');
const c2=document.querySelector('#c2');
const c3=document.querySelector('#c3');
const c4=document.querySelector('#c4');
const c5=document.querySelector('#c5');
const c6=document.querySelector('#c6');
const c7=document.querySelector('#c7');
const c8=document.querySelector('#c8');
const c9=document.querySelector('#c9');
const c10=document.querySelector('#c10');
const c11=document.querySelector('#c11');
const c12=document.querySelector('#c12');
const c13=document.querySelector('#c13');
const c14=document.querySelector('#c14');
const c15=document.querySelector('#c15');
const c16=document.querySelector('#c16');
const c17=document.querySelector('#c17');
const c18=document.querySelector('#c18');
const c19=document.querySelector('#c19');
const c20=document.querySelector('#c20');
if (asem=="http://127.0.0.1:3000/dok.html#semua"){
semua.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#awal"){
semua.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#login"){
semua.classList.toggle('hidden')
a2.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#daftar"){
semua.classList.toggle('hidden')
a1.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#configurasi"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#username%20configurasi"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
b2.classList.toggle('hidden')
b3.classList.toggle('hidden')
b4.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#background"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
b1.classList.toggle('hidden')
b3.classList.toggle('hidden')
b4.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#foreground"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
b1.classList.toggle('hidden')
b3.classList.toggle('hidden')
b4.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#background%20foreground"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
b1.classList.toggle('hidden')
b3.classList.toggle('hidden')
b4.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#cek%20masker"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
b1.classList.toggle('hidden')
b2.classList.toggle('hidden')
b4.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#cek%20ultha%20jenis%20fonts"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
b1.classList.toggle('hidden')
b2.classList.toggle('hidden')
b3.classList.toggle('hidden')
utama.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#cek%20ultha"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
b1.classList.toggle('hidden')
b2.classList.toggle('hidden')
b3.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#jenis%20fonts"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
b1.classList.toggle('hidden')
b2.classList.toggle('hidden')
b3.classList.toggle('hidden')
utama.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#utama"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#halaman%20utama"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
fitur.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#fitur"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#kalkulator"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#ai"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#neko"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#youtube%20dowloader"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#film"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#filter%20gambar"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#pengaturan%20akun"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#biografi"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#chatting"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#file%20explorer"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#google"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#web"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#sos"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#editing"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#scanner"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#keberuntungan"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#notes"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#alkitab"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c19.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#link%20shorten"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c20.classList.toggle('hidden')
}else if (asem=="http://127.0.0.1:3000/dok.html#grooming%20hewan"){
semua.classList.toggle('hidden')
awal.classList.toggle('hidden')
configurasi.classList.toggle('hidden')
utama.classList.toggle('hidden')
c1.classList.toggle('hidden')
c2.classList.toggle('hidden')
c3.classList.toggle('hidden')
c4.classList.toggle('hidden')
c5.classList.toggle('hidden')
c6.classList.toggle('hidden')
c7.classList.toggle('hidden')
c8.classList.toggle('hidden')
c9.classList.toggle('hidden')
c10.classList.toggle('hidden')
c11.classList.toggle('hidden')
c12.classList.toggle('hidden')
c13.classList.toggle('hidden')
c14.classList.toggle('hidden')
c15.classList.toggle('hidden')
c16.classList.toggle('hidden')
c17.classList.toggle('hidden')
c18.classList.toggle('hidden')
c19.classList.toggle('hidden')
}


